lang: python
compiler: gcc
sudo: require
dist: trusty

python:
  - "3.6"
  
env:
  global:
    - PYBIND11_VERSION="2.2.4"

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq
  - wget https://github.com/pybind/pybind11/archive/v${PYBIND11_VERSION}.tar.gz
  - tar xf v${PYBIND11_VERSION}.tar.gz
  - mv pybind11-${PYBIND11_VERSION} ${HOME}
  - export pybind11_DIR=$HOME/pybind11-${PYBIND11_VERSION}
  
install:
  - sudo apt-get -y install qt59base libgl1-mesa-dev libarmadillo-dev libgoogle-glog-dev python3
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cd $pybind11_DIR
  - cmake . && make && sudo make install
  - find $pybind11_DIR
  - cd -
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_PREFIX_PATH=$pybind11_DIR
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh APPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
