compiler: gcc
sudo: require
language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

script:
  - ./build-scripts/build-omm-ubuntu.sh
  - if [ "$TRAVIS_DIST" = "xenial" ]; then ./build-scripts/make-appimage.sh; fi
after_success:
  - if [ "$TRAVIS_DIST" = "xenial" ]; then ./build-scripts/upload-appimage.sh; fi
  - touch success

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
