compiler: gcc
sudo: require
language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9931d1c2db52be0aa323
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

script:
  - ./build-scripts/build-omm-ubuntu.sh
  - if [ "$TRAVIS_DIST" = "xenial" ]; then ./build-scripts/make-appimage.sh; fi
after_success:
  - if [ "$TRAVIS_DIST" = "xenial" ]; then ./build-scripts/upload-appimage.sh; fi
  - touch success

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

