compiler: gcc
sudo: require
language: cpp

services:
  - xvfb

jobs:
  include:
    - name: "Build on Ubuntu Xenial"
      os: linux
      dist: xenial
      - stage: "build"
        script:
          - ./build-scripts/build-omm-ubuntu.sh
          - ./build-scripts/make-appimage.sh; fi
        after_success:
          - then ./build-scripts/upload-appimage.sh; fi
          - touch success
      - stage: "test"
        script: build/test/unit/ommpfritt_unit_tests
    - name: "Build on Ubuntu Bionic"
      os: linux
      dist: bionic
      - stage: "build"
        script:
          - ./build-scripts/build-omm-ubuntu.sh
        after_success:
          - touch success
      - stage: "test"
        script: build/test/unit/ommpfritt_unit_tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9931d1c2db52be0aa323
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

