compiler: gcc
sudo: require
language: cpp

services:
  - xvfb

jobs:
  include:
    - stage: "build"
      os: linux
      dist: xenial
      name: "Build on Ubuntu Xenial"
      script:
        - ./build-scripts/build-omm-ubuntu.sh
        - ./build-scripts/make-appimage.sh
      after_success:
        - ./build-scripts/upload-appimage.sh
        - touch success

    - stage: "test"
      name: "Test on Ubuntu Xenial"
      os: linux
      dist: xenial
      script: build/test/unit/ommpfritt_unit_tests

    - stage: "build"
      os: linux
      dist: bionic
      name: "Build on Ubuntu Bionic"
      script:
        - ./build-scripts/build-omm-ubuntu.sh
      after_success:
        - touch success

    - stage: "test"
      os: linux
      dist: bionic
      name: "Test on Ubuntu Bionic"
      script: build/test/unit/ommpfritt_unit_tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9931d1c2db52be0aa323
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

